from __future__ import annotations

import json
import shutil
import time
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

from .causal_data import (
    CancerDemoConfig,
    load_or_generate_cancer_data,
    validate_causal_frame,
)
from .causal_models import (
    build_causal_graph,
    build_evidence_ladder,
    causal_effects_table,
    estimate_binary_treatment_effect,
    estimate_transition_matrix,
    graph_tables,
    plot_causal_graph,
    plot_transition_matrix,
)
from .causal_report import generate_causal_report
from .active_learning import (
    ClosedLoopConfig,
    run_closed_loop_experimentation,
    write_closed_loop_outputs,
)
from .biomarkers import BiomarkerConfig, run_causal_biomarkers, write_biomarker_outputs
from .multimodal import (
    MODALITY_ORDER,
    MultimodalDemoConfig,
    evaluate_modality_ablation,
    feature_manifest,
    generate_multimodal_mudata,
    modality_feature_frame,
    modality_inventory,
    modality_summary_correlations,
    plot_correlation_matrix,
    plot_modality_ablation,
    read_csv_bundle,
    read_multimodal,
    validate_multimodal,
    write_csv_bundle,
    write_multimodal,
)
from .uncertainty import (
    BenchmarkResult,
    benchmark_linear_baselines,
    calibration_curve_table,
    plot_baseline_benchmark,
    plot_reliability,
    transition_bootstrap_uncertainty,
)
from .therapeutics import (
    TherapeuticConfig,
    run_counterfactual_therapeutics,
    write_therapeutic_outputs,
)
from .spatial import (
    SpatialGraphConfig,
    attach_spatial_to_mudata,
    build_spatial_heterograph,
    generate_spatial_coordinates,
    plot_communication_circuits,
    plot_contact_heatmap,
    plot_heterograph_summary,
    plot_niche_composition,
    plot_spatial_atlas,
    write_spatial_graph_outputs,
)
from .utils import ensure_dir, json_dump


def load_causal_config(path: str | Path) -> dict[str, Any]:
    with Path(path).open("r", encoding="utf-8") as handle:
        payload = yaml.safe_load(handle) or {}
    if not isinstance(payload, dict):
        raise ValueError("CausaFlux config must be a YAML mapping")
    return payload


def _resolve_path(value: str | Path | None, config_path: Path) -> Path | None:
    if value is None:
        return None
    path = Path(value)
    return path if path.is_absolute() else (config_path.parent / path).resolve()


def _stage(message: str, started: float | None = None) -> float:
    now = time.perf_counter()
    if started is None:
        print(f"[CausaFlux] {message}", flush=True)
    else:
        print(f"[CausaFlux] {message} ({now - started:.2f} s)", flush=True)
    return now


def _model_card(
    output_path: Path,
    config: dict[str, Any],
    validation: dict[str, Any],
    multimodal_validation: dict[str, Any],
    spatial_validation: dict[str, Any],
    state_metrics: dict[str, Any],
    therapeutic_qc: dict[str, Any],
    biomarker_qc: dict[str, Any] | None = None,
) -> None:
    biomarker_qc = biomarker_qc or {}
    output_path.write_text(
        "\n".join(
            [
                "# CausaFlux v1.7.0 closed-loop experimentation model card",
                "",
                "## Intended use",
                "Research software development, multimodal and spatial data harmonization, causal-method prototyping, uncertainty auditing, early-warning biomarker ranking, counterfactual therapeutic ranking, and closed-loop experiment-design demonstrations.",
                "",
                "## Multimodal data model",
                "RNA, ATAC, protein, mutation, and drug-response matrices are stored as aligned AnnData modalities inside one MuData object. Observation identity, donor, time, treatment, state, and assay-availability masks live on the shared observation axis.",
                "",
                "## Prohibited interpretation",
                "Bundled synthetic outputs are not experimental evidence, identified biological causal effects, clinical predictions, or treatment recommendations.",
                "",
                "## Multicellular spatial graph",
                "Cells are typed tumor, immune, stromal, or vascular nodes. Spatial proximity edges are separated from directed ligand-receptor communication edges. Niche labels and communication circuits are algorithmic hypotheses requiring experimental validation.",
                f"- Spatial nodes: {spatial_validation['n_nodes']}",
                f"- Proximity edges: {spatial_validation['n_spatial_edges']}",
                f"- Ligand-receptor edges: {spatial_validation['n_communication_edges']}",
                f"- Spatial niches: {spatial_validation['n_niches']}",
                "",
                "## Counterfactual therapeutics",
                "Gene, drug, combination, sequence, and timing predictions are generated by explicit intervention events that alter named state variables. A donor-audited resistance surrogate predicts the counterfactual outcome, while normal-cell toxicity is scored separately.",
                f"- Interventions: {therapeutic_qc['n_interventions']}",
                f"- Regimens: {therapeutic_qc['n_regimens']}",
                f"- Top synthetic regimen: {therapeutic_qc['top_regimen']}",
                f"- Pareto-optimal regimens: {therapeutic_qc['n_pareto_optimal']}",
                "",
                "## Causal biomarker engine",
                "Candidate rankings keep temporal lead, held-donor association, causal-graph proximity, perturbational support, assayability, redundancy, and donor-bootstrap uncertainty as separate evidence components before calculating a composite score.",
                f"- Candidate biomarkers: {biomarker_qc.get('n_candidates', 'not recorded')}",
                f"- Completed donor bootstraps: {biomarker_qc.get('bootstrap_completed', 'not recorded')}",
                f"- Top synthetic biomarker: {biomarker_qc.get('top_biomarker', 'not recorded')}",
                f"- Top compact panel: {biomarker_qc.get('top_panel', 'not recorded')}",
                "Causal proximity is a graph-based prioritization feature and does not establish that a measurement is causal.",
                "",
                "## Integration policy",
                "Early fusion concatenates prefixed modality features. Imputation and scaling are fit only inside each donor-held-out training fold. The release also reports single-modality and leave-one-modality-out comparisons.",
                "",
                "## Baseline and split policy",
                "All state-model comparisons use the same donor-held-out folds. No donor may appear in both training and test partitions within a fold.",
                "",
                "## Calibration and uncertainty",
                "Calibration is cross-fitted by donor. Metric intervals use donor-cluster bootstrap resampling. Ensemble uncertainty measures disagreement among transparent linear model families and is not a complete posterior distribution.",
                "",
                "## Causal assumptions",
                "The configured directed acyclic graph and measured covariates define the adjustment assumptions. Unmeasured confounding, positivity violations, measurement error, interference, and model misspecification can invalidate causal estimates.",
                "",
                "## Validation summary",
                f"- Biological rows: {validation['n_rows']}",
                f"- MuData observations: {multimodal_validation['n_obs']}",
                f"- Modalities: {', '.join(multimodal_validation['required_modalities'])}",
                f"- Split mode: {state_metrics['split_mode']}",
                f"- Selected fused state model: {state_metrics['selected_model']} ({state_metrics['selected_variant']})",
                f"- Donor-held-out balanced accuracy: {state_metrics['donor_grouped_balanced_accuracy']:.3f}",
                f"- Donor-held-out log loss: {state_metrics['donor_grouped_log_loss']:.3f}",
                f"- Expected calibration error: {state_metrics['expected_calibration_error']:.3f}",
                "",
                "## Reproducibility",
                f"- Seed: {config.get('experiment', {}).get('seed', 31)}",
                "- Complete configuration: experiment_config.yaml",
                "- MuData artifact: multimodal/causaflux_multimodal.h5mu",
                "- Exact fold assignments: baselines/donor_split_manifest.csv",
                "- Machine-readable outputs: CSV, JSON, H5MU, HTML, and image files.",
            ]
        ),
        encoding="utf-8",
    )


def run_causal_experiment(
    config_path: str | Path,
    output_dir: str | Path | None = None,
    *,
    stop_after_baseline: bool = False,
    resume_after_baseline: bool = False,
    stop_before_therapeutics: bool = False,
    stop_before_causal_effects: bool = False,
) -> dict[str, Path]:
    config_path = Path(config_path).resolve()
    config = load_causal_config(config_path)
    experiment = config.get("experiment", {})
    experiment_name = str(experiment.get("name", "CausaFlux v1.7.0 counterfactual therapeutics demo"))
    seed = int(experiment.get("seed", 31))
    output_dir = ensure_dir(output_dir or config.get("output", "causaflux_v1.7.0_output"))
    data_dir = ensure_dir(output_dir / "data")
    multimodal_dir = ensure_dir(output_dir / "multimodal")
    spatial_dir = ensure_dir(output_dir / "spatial_graph")
    states_dir = ensure_dir(output_dir / "states")
    baselines_dir = ensure_dir(output_dir / "baselines")
    calibration_dir = ensure_dir(output_dir / "calibration")
    uncertainty_dir = ensure_dir(output_dir / "uncertainty")
    transitions_dir = ensure_dir(output_dir / "transitions")
    graph_dir = ensure_dir(output_dir / "graph")
    causal_dir = ensure_dir(output_dir / "causal")
    biomarker_dir = ensure_dir(output_dir / "biomarkers")
    active_dir = ensure_dir(output_dir / "active_learning")
    therapeutics_dir = ensure_dir(output_dir / "therapeutics")
    report_dir = ensure_dir(output_dir / "report")
    shutil.copy2(config_path, output_dir / "experiment_config.yaml")

    if stop_after_baseline and resume_after_baseline:
        raise ValueError("stop_after_baseline and resume_after_baseline are mutually exclusive")

    if resume_after_baseline:
        stage = _stage("Resuming from serialized donor-aware baseline stage")
        frame = pd.read_csv(data_dir / "cancer_longitudinal.csv")
        with (data_dir / "validation_report.json").open("r", encoding="utf-8") as handle:
            validation = json.load(handle)
        multimodal_config = config.get("multimodal", {})
        mdata = read_csv_bundle(multimodal_dir / "csv_bundle")
        with (multimodal_dir / "validation_report.json").open("r", encoding="utf-8") as handle:
            multimodal_validation = json.load(handle)
        inventory = pd.read_csv(multimodal_dir / "modality_inventory.csv")
        manifest = pd.read_csv(multimodal_dir / "feature_manifest.csv")
        integrated_path = multimodal_dir / "integrated_feature_table.csv"
        integrated = pd.read_csv(integrated_path)
        state_features = manifest["fused_column"].astype(str).tolist()
        hardening = config.get("baseline_uncertainty", {})
        split_mode = str(hardening.get("split_mode", "leave_one_donor_out"))
        benchmark = BenchmarkResult(
            predictions=pd.read_csv(states_dir / "state_probabilities.csv"),
            all_predictions=pd.read_csv(baselines_dir / "all_oof_probabilities.csv"),
            metrics=pd.read_csv(baselines_dir / "linear_baseline_metrics.csv"),
            calibration_metrics=pd.read_csv(calibration_dir / "calibration_comparison.csv"),
            split_manifest=pd.read_csv(baselines_dir / "donor_split_manifest.csv").fillna(""),
            bootstrap_metrics=pd.read_csv(uncertainty_dir / "metric_bootstrap_intervals.csv"),
            ensemble_uncertainty=pd.read_csv(uncertainty_dir / "ensemble_uncertainty.csv"),
            bootstrap_predictions=pd.read_csv(uncertainty_dir / "donor_bootstrap_state_probabilities.csv"),
            selected_model=str(pd.read_json(states_dir / "state_metrics.json", typ="series")["selected_model"]),
            selected_variant=str(pd.read_json(states_dir / "state_metrics.json", typ="series")["selected_variant"]),
        )
        with (states_dir / "state_metrics.json").open("r", encoding="utf-8") as handle:
            state_metrics = json.load(handle)
        modality_metrics = pd.read_csv(multimodal_dir / "modality_ablation_metrics.csv")
        modality_contributions = pd.read_csv(multimodal_dir / "modality_contributions.csv")
        correlation = pd.read_csv(multimodal_dir / "cross_modal_summary_correlations.csv", index_col=0)
        modality_plot = multimodal_dir / "modality_ablation.png"
        correlation_plot = multimodal_dir / "cross_modal_correlation.png"
        stage = _stage("Serialized baseline stage restored", stage)
    else:
        # Biological/causal table remains explicit so downstream causal assumptions are
        # auditable rather than hidden inside a latent multimodal object.
        data_config = config.get("data", {})
        source = _resolve_path(data_config.get("path"), config_path)
        demo_config = CancerDemoConfig(
            n_donors=int(data_config.get("n_donors", 8)),
            clones_per_donor=int(data_config.get("clones_per_donor", 36)),
            non_tumor_cells_per_type=int(data_config.get("non_tumor_cells_per_type", 12)),
            times=tuple(float(value) for value in data_config.get("times", [0, 24, 72, 168])),
            seed=seed,
        )
        stage = _stage("Generating or loading biological data")
        frame = load_or_generate_cancer_data(str(data_config.get("mode", "synthetic")), source, demo_config)
        stage = _stage("Biological data ready", stage)
        validation = validate_causal_frame(frame)
        frame.to_csv(data_dir / "cancer_longitudinal.csv", index=False)
        json_dump(validation, data_dir / "validation_report.json")

        multimodal_config = config.get("multimodal", {})
        multimodal_mode = str(multimodal_config.get("mode", "synthetic")).lower()
        stage = _stage("Building aligned multimodal data")
        if multimodal_mode == "synthetic":
            mdata = generate_multimodal_mudata(
                frame,
                MultimodalDemoConfig(
                    seed=seed,
                    missing_modality_rate=float(multimodal_config.get("missing_modality_rate", 0.03)),
                ),
            )
        elif multimodal_mode == "h5mu":
            path = _resolve_path(multimodal_config.get("path"), config_path)
            if path is None:
                raise ValueError("multimodal.path is required when multimodal.mode='h5mu'")
            mdata = read_multimodal(path)
        elif multimodal_mode == "csv_bundle":
            path = _resolve_path(multimodal_config.get("path"), config_path)
            if path is None:
                raise ValueError("multimodal.path is required when multimodal.mode='csv_bundle'")
            mdata = read_csv_bundle(path)
        else:
            raise ValueError("multimodal.mode must be synthetic, h5mu, or csv_bundle")

        multimodal_validation = validate_multimodal(mdata)
        stage = _stage("Multimodal object ready", stage)
        frame_rows = set(frame["row_id"].astype(str))
        multimodal_rows = set(mdata.obs_names.astype(str))
        if frame_rows != multimodal_rows:
            missing_in_mudata = sorted(frame_rows - multimodal_rows)[:10]
            missing_in_frame = sorted(multimodal_rows - frame_rows)[:10]
            raise ValueError(
                "Causal table and MuData observation axes differ. "
                f"Missing in MuData: {missing_in_mudata}; missing in table: {missing_in_frame}"
            )

        # Prepare the exact multimodal matrix before spatial/HDF5 native-library
        # operations. This ordering prevents solver interactions observed in some
        # scientific Python stacks while preserving the same exported artifacts.
        inventory = modality_inventory(mdata)
        manifest = feature_manifest(mdata)
        inventory.to_csv(multimodal_dir / "modality_inventory.csv", index=False)
        manifest.to_csv(multimodal_dir / "feature_manifest.csv", index=False)
        json_dump(multimodal_validation, multimodal_dir / "validation_report.json")
        if bool(multimodal_config.get("export_csv_bundle", True)):
            write_csv_bundle(mdata, multimodal_dir / "csv_bundle")

        integrated = modality_feature_frame(mdata, MODALITY_ORDER)
        stage = _stage("Multimodal modeling table ready", stage)
        integrated_path = multimodal_dir / "integrated_feature_table.csv"
        integrated.to_csv(integrated_path, index=False)
        # Re-read the exported matrix to create a compact, version-robust modeling
        # boundary. The exact table used by estimators is therefore the auditable
        # CSV artifact shipped with every run.
        integrated = pd.read_csv(integrated_path)
        state_features = manifest["fused_column"].tolist()

        hardening = config.get("baseline_uncertainty", {})
        split_mode = str(hardening.get("split_mode", "leave_one_donor_out"))
        stage = _stage("Evaluating modality ablations")
        modality_metrics, modality_contributions = evaluate_modality_ablation(
            integrated,
            split_mode=split_mode,
            n_splits=int(hardening.get("n_splits", 4)),
            seed=seed,
        )
        modality_metrics.to_csv(multimodal_dir / "modality_ablation_metrics.csv", index=False)
        modality_contributions.to_csv(multimodal_dir / "modality_contributions.csv", index=False)
        modality_plot = plot_modality_ablation(
            modality_metrics, multimodal_dir / "modality_ablation.png"
        )
        correlation = modality_summary_correlations(mdata)
        correlation.to_csv(multimodal_dir / "cross_modal_summary_correlations.csv")
        correlation_plot = plot_correlation_matrix(
            correlation, multimodal_dir / "cross_modal_correlation.png"
        )

        stage = _stage("Modality diagnostics ready", stage)
        stage = _stage("Running donor-aware baselines, calibration, and uncertainty")
        benchmark = benchmark_linear_baselines(
            integrated,
            features=state_features,
            split_mode=split_mode,
            n_splits=int(hardening.get("n_splits", 4)),
            calibration_methods=tuple(hardening.get("calibration_methods", ["sigmoid", "isotonic"])),
            n_metric_bootstrap=int(hardening.get("metric_bootstrap", 200)),
            n_prediction_bootstrap=int(hardening.get("prediction_bootstrap", 40)),
            bootstrap_model=str(hardening.get("bootstrap_model", "logistic_l2")),
            seed=seed,
        )
        stage = _stage("Baseline and uncertainty benchmark ready", stage)
        benchmark.predictions.to_csv(states_dir / "state_probabilities.csv", index=False)
        benchmark.all_predictions.to_csv(baselines_dir / "all_oof_probabilities.csv", index=False)
        benchmark.metrics.to_csv(baselines_dir / "linear_baseline_metrics.csv", index=False)
        benchmark.split_manifest.to_csv(baselines_dir / "donor_split_manifest.csv", index=False)
        benchmark.calibration_metrics.to_csv(calibration_dir / "calibration_comparison.csv", index=False)
        benchmark.bootstrap_metrics.to_csv(uncertainty_dir / "metric_bootstrap_intervals.csv", index=False)
        benchmark.ensemble_uncertainty.to_csv(uncertainty_dir / "ensemble_uncertainty.csv", index=False)
        benchmark.bootstrap_predictions.to_csv(
            uncertainty_dir / "donor_bootstrap_state_probabilities.csv", index=False
        )

        selected_metric = benchmark.metrics.loc[
            (benchmark.metrics["model"] == benchmark.selected_model)
            & (benchmark.metrics["variant"] == benchmark.selected_variant)
        ].iloc[0]
        state_metrics = {
            "selected_model": benchmark.selected_model,
            "selected_variant": benchmark.selected_variant,
            "representation": "early_fusion_prefixed_features",
            "modalities": ";".join(MODALITY_ORDER),
            "n_multimodal_features": int(len(state_features)),
            "split_mode": split_mode,
            "donor_grouped_balanced_accuracy": float(selected_metric["balanced_accuracy"]),
            "donor_grouped_log_loss": float(selected_metric["log_loss"]),
            "brier_score": float(selected_metric["brier_score"]),
            "expected_calibration_error": float(selected_metric["expected_calibration_error"]),
            "classwise_ece": float(selected_metric["classwise_ece"]),
            "n_tumor_rows": int((frame["cell_type"] == "tumor").sum()),
            "n_donors": int(frame["donor_id"].nunique()),
            "n_linear_models": int(benchmark.metrics["model"].nunique()),
            "metric_bootstrap": int(hardening.get("metric_bootstrap", 200)),
            "prediction_bootstrap": int(hardening.get("prediction_bootstrap", 40)),
            "bootstrap_reference_model": str(hardening.get("bootstrap_model", "logistic_l2")),
        }
        json_dump(state_metrics, states_dir / "state_metrics.json")


        if stop_after_baseline:
            json_dump(
                {
                    "stage": "baseline_complete",
                    "framework": "CausaFlux",
                    "version": "1.7.0",
                    "selected_model": benchmark.selected_model,
                    "selected_variant": benchmark.selected_variant,
                },
                output_dir / "stage_status.json",
            )
            return {
                "output_dir": output_dir,
                "integrated_table": integrated_path,
                "state_probabilities": states_dir / "state_probabilities.csv",
                "stage_status": output_dir / "stage_status.json",
            }

    benchmark_plot = baselines_dir / "linear_baseline_benchmark.png"
    plot_baseline_benchmark(benchmark.metrics, benchmark_plot)
    selected_curve = calibration_curve_table(benchmark.predictions, "probability_")
    ensemble_curve = calibration_curve_table(benchmark.ensemble_uncertainty, "ensemble_probability_")
    selected_curve.to_csv(calibration_dir / "selected_model_reliability.csv", index=False)
    ensemble_curve.to_csv(calibration_dir / "ensemble_reliability.csv", index=False)
    reliability_plot = calibration_dir / "reliability_diagram.png"
    plot_reliability(selected_curve, ensemble_curve, reliability_plot)

    spatial_payload = config.get("spatial_graph", {})
    spatial_config = SpatialGraphConfig(
        seed=seed,
        width=float(spatial_payload.get("width", 1000.0)),
        height=float(spatial_payload.get("height", 1000.0)),
        n_tumor_nests=int(spatial_payload.get("n_tumor_nests", 3)),
        k_neighbors=int(spatial_payload.get("k_neighbors", 8)),
        max_distance=float(spatial_payload.get("max_distance", 230.0)),
        neighborhood_radius=float(spatial_payload.get("neighborhood_radius", 180.0)),
        communication_radius=float(spatial_payload.get("communication_radius", 190.0)),
        min_circuit_edges=int(spatial_payload.get("min_circuit_edges", 3)),
        bootstrap=int(spatial_payload.get("bootstrap", 50)),
        export_graphml=bool(spatial_payload.get("export_graphml", True)),
    )
    coordinate_mode = str(spatial_payload.get("coordinate_mode", "synthetic")).lower()
    if coordinate_mode == "synthetic" or not {"spatial_x", "spatial_y"}.issubset(frame.columns):
        frame = generate_spatial_coordinates(frame, spatial_config)
    elif coordinate_mode not in {"existing", "synthetic"}:
        raise ValueError("spatial_graph.coordinate_mode must be synthetic or existing")
    attach_spatial_to_mudata(mdata, frame)
    stage = _stage("Building multicellular spatial heterograph")
    spatial_result = build_spatial_heterograph(frame, spatial_config)
    stage = _stage("Spatial heterograph ready", stage)
    spatial_paths = write_spatial_graph_outputs(
        spatial_result, spatial_dir, export_graphml=spatial_config.export_graphml
    )
    spatial_atlas_plot = plot_spatial_atlas(
        spatial_result.nodes, spatial_dir / "spatial_atlas.png", spatial_payload.get("representative_sample")
    )
    contact_plot = plot_contact_heatmap(
        spatial_result.contact_enrichment, spatial_dir / "contact_enrichment_heatmap.png"
    )
    circuit_plot = plot_communication_circuits(
        spatial_result.circuits, spatial_dir / "communication_circuits.png",
        top_n=int(spatial_payload.get("top_circuits", 12)),
    )
    heterograph_plot = plot_heterograph_summary(
        spatial_result.nodes, spatial_result.communication_edges, spatial_dir / "heterograph_summary.png"
    )
    niche_plot = plot_niche_composition(
        spatial_result.niche_summary, spatial_dir / "spatial_niche_composition.png"
    )
    frame = spatial_result.frame
    frame.to_csv(data_dir / "cancer_longitudinal.csv", index=False)

    stage = _stage("Writing spatially aligned MuData exports")
    mudata_path = write_multimodal(mdata, multimodal_dir / "causaflux_multimodal.h5mu")
    if bool(multimodal_config.get("export_csv_bundle", True)):
        write_csv_bundle(mdata, multimodal_dir / "csv_bundle")
    stage = _stage("Spatial and MuData exports ready", stage)

    stage = _stage("Estimating disease transitions")
    transition_matrix, next_state_predictions = estimate_transition_matrix(frame)
    transition_matrix.to_csv(transitions_dir / "transition_matrix.csv")
    next_state_predictions.to_csv(transitions_dir / "next_state_predictions.csv", index=False)
    transition_uncertainty = transition_bootstrap_uncertainty(
        frame,
        n_bootstrap=int(hardening.get("transition_bootstrap", hardening.get("metric_bootstrap", 200))),
        seed=seed + 303,
    )
    transition_uncertainty.to_csv(transitions_dir / "transition_bootstrap_intervals.csv", index=False)
    transition_plot = transitions_dir / "transition_heatmap.png"
    plot_transition_matrix(transition_matrix, transition_plot)

    stage = _stage("Disease transitions ready", stage)
    stage = _stage("Building causal graph and treatment effects")
    graph_config = config.get("causal_graph", {})
    graph = build_causal_graph(graph_config.get("nodes", []), graph_config.get("edges", []))
    nodes, edges = graph_tables(graph)
    nodes.to_csv(graph_dir / "causal_nodes.csv", index=False)
    edges.to_csv(graph_dir / "causal_edges.csv", index=False)
    graph_plot = graph_dir / "causal_graph.png"
    plot_causal_graph(graph, graph_plot, title="CausaFlux v1.7.0 editable causal graph")

    if stop_before_causal_effects:
        json_dump(
            {
                "stage": "spatial_graph_complete",
                "framework": "CausaFlux",
                "version": "1.7.0",
                "spatial_nodes": int(spatial_result.qc["n_nodes"]),
            },
            output_dir / "stage_status.json",
        )
        return {
            "output_dir": output_dir,
            "mudata": mudata_path,
            "spatial_nodes": spatial_paths["nodes"],
            "stage_status": output_dir / "stage_status.json",
        }

    tumor = frame.loc[frame["cell_type"] == "tumor"].copy()
    final_time = tumor["time_hours"].max()
    final_tumor = tumor.loc[tumor["time_hours"] == final_time].copy()
    baseline_names = [
        "mutation_burden",
        "enhancer_plasticity",
        "mitochondrial_reserve",
        "antigen_presentation",
        "ire1_xbp1",
    ]
    baseline = (
        tumor.sort_values("time_hours")
        .groupby("lineage_id", as_index=False)
        .first()[["lineage_id", *baseline_names]]
        .rename(columns={name: f"baseline_{name}" for name in baseline_names})
    )
    final_tumor = final_tumor.merge(baseline, on="lineage_id", how="left")
    covariates = config.get("causal_estimation", {}).get(
        "covariates",
        [
            "donor_id",
            "baseline_mutation_burden",
            "baseline_enhancer_plasticity",
            "baseline_mitochondrial_reserve",
            "baseline_antigen_presentation",
            "baseline_ire1_xbp1",
        ],
    )
    comparator = str(config.get("causal_estimation", {}).get("comparator", "standard_therapy"))
    treatment_arms = config.get("causal_estimation", {}).get(
        "treatments", ["standard_plus_ire1i", "standard_plus_mitoi", "standard_plus_ifng"]
    )
    bootstrap = int(config.get("causal_estimation", {}).get("bootstrap", 120))
    effect_results = []
    counterfactual_frames = []
    for treatment in treatment_arms:
        result, counterfactuals = estimate_binary_treatment_effect(
            final_tumor,
            treatment_arm=str(treatment),
            comparator=comparator,
            outcome_column="future_resistant",
            covariates=covariates,
            n_bootstrap=bootstrap,
            seed=seed,
        )
        effect_results.append(result)
        counterfactual_frames.append(counterfactuals)
    effects = causal_effects_table(effect_results)
    effects.to_csv(causal_dir / "causal_effects.csv", index=False)
    counterfactuals = pd.concat(counterfactual_frames, ignore_index=True)
    counterfactuals.to_csv(causal_dir / "counterfactual_predictions.csv", index=False)
    evidence = build_evidence_ladder(effects)
    evidence.to_csv(causal_dir / "evidence_ladder.csv", index=False)

    if stop_before_therapeutics:
        json_dump(
            {
                "stage": "spatial_causal_complete",
                "framework": "CausaFlux",
                "version": "1.7.0",
                "spatial_nodes": int(spatial_result.qc["n_nodes"]),
                "causal_effects": int(len(effects)),
            },
            output_dir / "stage_status.json",
        )
        return {
            "output_dir": output_dir,
            "mudata": mudata_path,
            "effects": causal_dir / "causal_effects.csv",
            "stage_status": output_dir / "stage_status.json",
        }

    therapeutic_payload = config.get("therapeutics", {})
    therapeutic_config = TherapeuticConfig(
        comparator=str(therapeutic_payload.get("comparator", comparator)),
        decision_time_hours=float(therapeutic_payload.get("decision_time_hours", 24.0)),
        horizon_hours=float(therapeutic_payload.get("horizon_hours", final_time)),
        timing_grid=tuple(float(value) for value in therapeutic_payload.get("timing_grid", [0, 24, 48, 72, 120])),
        default_start_hour=float(therapeutic_payload.get("default_start_hour", 24.0)),
        sequence_delay_hours=float(therapeutic_payload.get("sequence_delay_hours", 24.0)),
        bootstrap=int(therapeutic_payload.get("bootstrap", 30)),
        max_reference_rows_per_donor=int(therapeutic_payload.get("max_reference_rows_per_donor", 30)),
        seed=seed,
        uncertainty_penalty=float(therapeutic_payload.get("uncertainty_penalty", 0.12)),
        normal_toxicity_weight=float(therapeutic_payload.get("normal_toxicity_weight", 0.30)),
    )
    stage = _stage("Predicting counterfactual therapeutics", stage)
    therapeutic_result = run_counterfactual_therapeutics(
        frame,
        therapeutic_config,
        intervention_overrides=therapeutic_payload.get("interventions", []),
    )
    therapeutic_paths = write_therapeutic_outputs(
        therapeutic_result, therapeutics_dir, therapeutic_config
    )
    stage = _stage("Counterfactual therapeutic predictions ready", stage)

    biomarker_config = config.get("biomarkers", {})
    stage = _stage("Causal effects ready", stage)
    stage = _stage("Ranking biomarkers and experiments")
    biomarker_engine_config = BiomarkerConfig(
        outcome_column=str(biomarker_config.get("outcome_column", "future_resistant")),
        cell_type=str(biomarker_config.get("cell_type", "tumor")),
        target_node=str(biomarker_config.get("target_node", "stable_resistance")),
        warning_auc_threshold=float(biomarker_config.get("warning_auc_threshold", 0.65)),
        warning_stability_threshold=float(biomarker_config.get("warning_stability_threshold", 0.60)),
        bootstrap=int(biomarker_config.get("bootstrap", 80)),
        top_panel_size=int(biomarker_config.get("top_panel_size", 3)),
        seed=seed,
    )
    biomarker_result = run_causal_biomarkers(
        frame, graph, biomarker_config.get("features", []), biomarker_engine_config,
        assayability=biomarker_config.get("assayability", {}),
        metadata_overrides=biomarker_config.get("metadata_overrides", {}),
    )
    biomarker_paths = write_biomarker_outputs(biomarker_result, biomarker_dir, write_plots=True)
    biomarkers = biomarker_result.ranking
    biomarker_plot = biomarker_paths["ranking_plot"]

    closed_loop_payload = config.get("closed_loop", {})
    closed_loop_config = ClosedLoopConfig(
        budget=float(closed_loop_payload.get("budget", 2.4)),
        batch_size=int(closed_loop_payload.get("batch_size", 4)),
        round2_budget=float(closed_loop_payload.get("round2_budget", 2.0)),
        round2_batch_size=int(closed_loop_payload.get("round2_batch_size", 3)),
        max_per_type=int(closed_loop_payload.get("max_per_type", 2)),
        require_type_coverage=bool(closed_loop_payload.get("require_type_coverage", True)),
        diversity_penalty=float(closed_loop_payload.get("diversity_penalty", 0.10)),
        information_gain_weight=float(closed_loop_payload.get("information_gain_weight", 0.40)),
        therapeutic_value_weight=float(closed_loop_payload.get("therapeutic_value_weight", 0.22)),
        biomarker_value_weight=float(closed_loop_payload.get("biomarker_value_weight", 0.13)),
        temporal_value_weight=float(closed_loop_payload.get("temporal_value_weight", 0.10)),
        feasibility_weight=float(closed_loop_payload.get("feasibility_weight", 0.15)),
        bootstrap=int(closed_loop_payload.get("bootstrap", 60)),
        eig_samples=int(closed_loop_payload.get("eig_samples", 1200)),
        seed=seed,
        simulate_demonstration_round=bool(closed_loop_payload.get("simulate_demonstration_round", True)),
        true_hypothesis=closed_loop_payload.get("true_hypothesis"),
    )
    closed_loop_result = run_closed_loop_experimentation(
        hypotheses_payload=closed_loop_payload.get("hypotheses") or None,
        candidates_payload=closed_loop_payload.get("candidates") or None,
        config=closed_loop_config,
        therapeutic_predictions=therapeutic_result.predictions,
        biomarkers=biomarker_result.ranking,
        biomarker_timecourse=biomarker_result.timecourse,
        transition_uncertainty=transition_uncertainty,
    )
    closed_loop_paths = write_closed_loop_outputs(closed_loop_result, active_dir, write_plots=True)
    recommendations = closed_loop_result.round1_ranking

    stage = _stage("Biomarkers and experiments ready", stage)
    stage = _stage("Generating report and manifest")
    report = generate_causal_report(
        report_dir / "index.html",
        experiment_name=experiment_name,
        validation=validation,
        multimodal_validation=multimodal_validation,
        modality_inventory=inventory,
        modality_metrics=modality_metrics,
        modality_contributions=modality_contributions,
        modality_plot=modality_plot,
        correlation_plot=correlation_plot,
        spatial_validation=spatial_result.qc,
        spatial_nodes=spatial_result.nodes,
        spatial_circuits=spatial_result.circuits,
        niche_summary=spatial_result.niche_summary,
        contact_enrichment=spatial_result.contact_enrichment,
        spatial_atlas_plot=spatial_atlas_plot,
        contact_plot=contact_plot,
        circuit_plot=circuit_plot,
        heterograph_plot=heterograph_plot,
        niche_plot=niche_plot,
        therapeutic_qc=therapeutic_result.qc,
        therapeutic_predictions=therapeutic_result.predictions,
        therapeutic_model_metrics={k: v for k, v in therapeutic_result.model_metrics.items() if k != "split_manifest"},
        therapeutic_ranking_plot=therapeutic_paths["ranking_plot"],
        therapeutic_timing_plot=therapeutic_paths["timing_plot"],
        therapeutic_sequence_plot=therapeutic_paths["sequence_plot"],
        therapeutic_pareto_plot=therapeutic_paths["pareto_plot"],
        therapeutic_waterfall_plot=therapeutic_paths["waterfall_plot"],
        state_metrics=state_metrics,
        baseline_metrics=benchmark.metrics,
        bootstrap_metrics=benchmark.bootstrap_metrics,
        transition_matrix=transition_matrix,
        transition_uncertainty=transition_uncertainty,
        effects=effects,
        evidence=evidence,
        biomarkers=biomarkers,
        recommendations=recommendations,
        transition_plot=transition_plot,
        graph_plot=graph_plot,
        biomarker_plot=biomarker_plot,
        biomarker_qc=biomarker_result.qc,
        biomarker_timecourse=biomarker_result.timecourse,
        biomarker_panels=biomarker_result.panels,
        biomarker_assays=biomarker_result.assay_manifest,
        biomarker_heatmap_plot=biomarker_paths["heatmap_plot"],
        biomarker_causal_lead_plot=biomarker_paths["causal_lead_plot"],
        biomarker_panel_plot=biomarker_paths["panel_plot"],
        active_learning_qc=closed_loop_result.qc,
        round1_batch=closed_loop_result.round1_batch,
        round2_recommendations=closed_loop_result.round2_ranking,
        posterior_history=closed_loop_result.posterior_history,
        experiment_ranking_plot=closed_loop_paths["ranking_plot"],
        information_gain_plot=closed_loop_paths["type_plot"],
        posterior_update_plot=closed_loop_paths["posterior_plot"],
        batch_portfolio_plot=closed_loop_paths["batch_plot"],
        sampling_time_plot=closed_loop_paths["sampling_plot"],
        benchmark_plot=benchmark_plot,
        reliability_plot=reliability_plot,
    )
    _model_card(
        output_dir / "model_card.md", config, validation, multimodal_validation,
        spatial_result.qc, state_metrics, therapeutic_result.qc, biomarker_result.qc
    )
    json_dump(
        {
            "framework": "CausaFlux",
            "version": "1.7.0",
            "experiment": experiment_name,
            "config": "experiment_config.yaml",
            "output": ".",
            "data_rows": int(len(frame)),
            "mudata": "multimodal/causaflux_multimodal.h5mu",
            "modalities": list(MODALITY_ORDER),
            "multimodal_features": int(len(state_features)),
            "spatial_nodes": int(spatial_result.qc["n_nodes"]),
            "spatial_edges": int(spatial_result.qc["n_spatial_edges"]),
            "communication_edges": int(spatial_result.qc["n_communication_edges"]),
            "spatial_niches": int(spatial_result.qc["n_niches"]),
            "top_spatial_circuit": spatial_result.circuits.iloc[0]["circuit"] if not spatial_result.circuits.empty else None,
            "therapeutic_interventions": int(therapeutic_result.qc["n_interventions"]),
            "therapeutic_regimens": int(therapeutic_result.qc["n_regimens"]),
            "top_therapeutic_regimen": therapeutic_result.qc["top_regimen"],
            "top_therapeutic_category": therapeutic_result.qc["top_category"],
            "selected_state_model": benchmark.selected_model,
            "selected_calibration": benchmark.selected_variant,
            "split_mode": split_mode,
            "top_biomarker": biomarkers.iloc[0]["biomarker"] if not biomarkers.empty else None,
            "top_biomarker_score": float(biomarkers.iloc[0]["causal_biomarker_score"]) if not biomarkers.empty else None,
            "biomarker_candidates": int(biomarker_result.qc["n_candidates"]),
            "biomarker_bootstraps": int(biomarker_result.qc["bootstrap_completed"]),
            "top_biomarker_panel": biomarker_result.qc.get("top_panel"),
            "top_biomarker_panel_auc": biomarker_result.qc.get("top_panel_auc"),
            "closed_loop_candidates": int(closed_loop_result.qc["n_candidates"]),
            "closed_loop_round1_batch_size": int(closed_loop_result.qc["round1_batch_size"]),
            "closed_loop_round1_cost": float(closed_loop_result.qc["round1_cost"]),
            "closed_loop_posterior_entropy_nats": float(closed_loop_result.qc["posterior_entropy_nats"]),
            "top_experiment": recommendations.iloc[0]["experiment_name"] if not recommendations.empty else None,
            "top_next_round_experiment": closed_loop_result.round2_ranking.iloc[0]["experiment_name"] if not closed_loop_result.round2_ranking.empty else None,
        },
        output_dir / "run_manifest.json",
    )
    _stage("Report and manifest ready", stage)
    print(f"CausaFlux v1.7.0 closed-loop experiment complete: {output_dir}")
    print(f"MuData: {mudata_path}")
    print(f"HTML report: {report}")
    return {
        "output_dir": output_dir,
        "data": data_dir / "cancer_longitudinal.csv",
        "mudata": mudata_path,
        "modality_metrics": multimodal_dir / "modality_ablation_metrics.csv",
        "spatial_nodes": spatial_paths["nodes"],
        "spatial_edges": spatial_paths["spatial_edges"],
        "communication_edges": spatial_paths["communication_edges"],
        "spatial_circuits": spatial_paths["circuits"],
        "baseline_metrics": baselines_dir / "linear_baseline_metrics.csv",
        "uncertainty": uncertainty_dir / "ensemble_uncertainty.csv",
        "effects": causal_dir / "causal_effects.csv",
        "biomarkers": biomarker_dir / "biomarker_ranking.csv",
        "recommendations": active_dir / "experiment_recommendations.csv",
        "therapeutic_predictions": therapeutic_paths["predictions"],
        "therapeutic_recommendations": therapeutic_paths["top"],
        "report": report,
    }
