from __future__ import annotations

import hashlib
import json
import math
from dataclasses import asdict, dataclass
from io import StringIO
from pathlib import Path
from typing import Any, Mapping

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, roc_auc_score
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from .utils import json_dump
from .visualization.publication import COLORS, apply_publication_style, export_figure

VERSION = "1.7.0"
CELL_TYPES = ("tumor", "macrophage", "t_cell", "fibroblast", "vascular")
RELATIONS = (
    "tumor_to_macrophage", "macrophage_to_tumor", "macrophage_to_t_cell",
    "fibroblast_to_tumor", "fibroblast_to_t_cell", "t_cell_to_tumor",
    "vascular_to_tumor", "other",
)
MODEL_ORDER = (
    "CellIntrinsicContinuous",
    "UngatedNeighborhoodContinuous",
    "NicheformerAdapterProxy",
    "CausaFluxSpatiotemporalGNN",
)
SPLIT_REGIMES = ("heldout_section", "heldout_donor")


@dataclass
class SpatiotemporalTissueConfig:
    seed: int = 160
    n_donors: int = 12
    sections_per_donor: int = 2
    cells_per_section: int = 36
    timepoints: tuple[float, ...] = (0.0, 12.0, 24.0, 48.0)
    k_neighbors: int = 5
    ridge_alpha: float = 1.0
    gate_C: float = 2.0
    bootstrap_replicates: int = 100
    section_test_fraction: float = 0.25
    donor_test_count: int = 3
    donor_validation_count: int = 2


@dataclass
class SpatiotemporalTissueData:
    nodes: pd.DataFrame
    edges: pd.DataFrame
    regulatory_edges: pd.DataFrame
    organelle_edges: pd.DataFrame
    tissue_outcomes: pd.DataFrame


def nicheformer_adapter_spec() -> dict[str, Any]:
    return {
        "name": "Nicheformer",
        "role": "external spatial foundation-model encoder",
        "upstream_project": "theislab/nicheformer",
        "citation": "Tejada-Lapuerta et al., Nature Methods 22, 2525-2538 (2025), doi:10.1038/s41592-025-02814-z",
        "required_inputs": ["row_id", "spatial transcriptomic or single-cell expression accepted by the user-managed Nicheformer environment"],
        "prediction_contract": "row_id,niche_embedding_0..niche_embedding_k",
        "execution_boundary": "CausaFlux does not redistribute Nicheformer checkpoints. The bundled proxy tests only the adapter and niche-context contract; scientific comparisons require embeddings generated by the official model in a user-managed environment.",
    }


def write_nicheformer_adapter(output_dir: str | Path) -> Path:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "nicheformer_adapter.json"
    json_dump(nicheformer_adapter_spec(), path)
    return path


def _sigmoid(x: np.ndarray | float) -> np.ndarray | float:
    return 1.0 / (1.0 + np.exp(-np.asarray(x)))


def _relation(sender: str, receiver: str) -> str:
    label = f"{sender}_to_{receiver}"
    return label if label in RELATIONS else "other"


def _cell_type_effect(cell_type: str) -> tuple[float, float, float, float]:
    # stress, damage, reserve, inflammatory/communication tone
    return {
        "tumor": (0.30, 0.25, -0.10, 0.20),
        "macrophage": (0.12, 0.10, 0.00, 0.55),
        "t_cell": (0.08, 0.04, 0.10, -0.12),
        "fibroblast": (0.10, 0.08, 0.05, 0.34),
        "vascular": (0.04, 0.03, 0.20, -0.05),
    }[cell_type]


def _relation_weight(relation: str) -> float:
    return {
        "tumor_to_macrophage": 0.75,
        "macrophage_to_tumor": 1.00,
        "macrophage_to_t_cell": 0.85,
        "fibroblast_to_tumor": 0.90,
        "fibroblast_to_t_cell": 0.72,
        "t_cell_to_tumor": -0.65,
        "vascular_to_tumor": -0.35,
        "other": 0.15,
    }[relation]


def _build_knn_edges(frame: pd.DataFrame, k: int) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for (section_id, time), group in frame.groupby(["section_id", "time"], sort=True):
        group = group.reset_index(drop=True)
        if len(group) < 2:
            continue
        n_neighbors = min(k + 1, len(group))
        nn = NearestNeighbors(n_neighbors=n_neighbors).fit(group[["x", "y"]].to_numpy())
        dist, idx = nn.kneighbors(group[["x", "y"]].to_numpy())
        for i in range(len(group)):
            for pos in range(1, n_neighbors):
                j = int(idx[i, pos])
                sender = group.iloc[j]
                receiver = group.iloc[i]
                rel = _relation(str(sender.cell_type), str(receiver.cell_type))
                ligand = float(sender.communication_tone + 0.45 * sender.stress + 0.25 * sender.damage)
                receptor = float(0.35 + 0.45 * receiver.vulnerability + 0.20 * receiver.stress)
                distance = float(dist[i, pos])
                true_gate_prob = float(_sigmoid(1.8 * _relation_weight(rel) + 1.15 * ligand + 0.75 * receptor - 0.018 * distance - 0.65))
                edge_active = int(true_gate_prob >= 0.50)
                rows.append({
                    "section_id": section_id,
                    "donor_id": receiver.donor_id,
                    "time": float(time),
                    "source": sender.row_id,
                    "target": receiver.row_id,
                    "source_cell_id": sender.cell_id,
                    "target_cell_id": receiver.cell_id,
                    "sender_type": sender.cell_type,
                    "receiver_type": receiver.cell_type,
                    "relation": rel,
                    "distance": distance,
                    "ligand_signal": ligand,
                    "receptor_signal": receptor,
                    "true_gate_probability": true_gate_prob,
                    "edge_active": edge_active,
                    "source_stress": float(sender.stress),
                    "source_damage": float(sender.damage),
                    "source_inflammation": float(sender.inflammation),
                })
    return pd.DataFrame(rows)


def _true_neighbor_message(edges: pd.DataFrame) -> pd.DataFrame:
    if edges.empty:
        return pd.DataFrame(columns=["row_id", "neigh_stress_true", "neigh_damage_true", "neigh_inflammation_true"])
    data = edges.copy()
    data["w"] = data.true_gate_probability / np.maximum(data.groupby(["section_id", "time", "target"]).true_gate_probability.transform("sum"), 1e-8)
    for src, out in [("source_stress", "neigh_stress_true"), ("source_damage", "neigh_damage_true"), ("source_inflammation", "neigh_inflammation_true")]:
        data[out] = data[src] * data.w
    agg = data.groupby("target", as_index=False)[["neigh_stress_true", "neigh_damage_true", "neigh_inflammation_true"]].sum()
    return agg.rename(columns={"target": "row_id"})


def generate_spatiotemporal_tissue_data(config: SpatiotemporalTissueConfig | None = None) -> SpatiotemporalTissueData:
    cfg = config or SpatiotemporalTissueConfig()
    rng = np.random.default_rng(cfg.seed)
    node_rows: list[dict[str, Any]] = []
    regulatory_rows: list[dict[str, Any]] = []
    organelle_rows: list[dict[str, Any]] = []

    # Persistent cells are followed through synthetic time-varying tissue snapshots.
    for donor_index in range(cfg.n_donors):
        donor_id = f"D{donor_index:02d}"
        donor_effect = rng.normal(0, 0.12, size=4)
        cohort_id = f"C{donor_index % 3}"
        for section_index in range(cfg.sections_per_donor):
            section_id = f"{donor_id}_S{section_index}"
            section_effect = rng.normal(0, 0.10, size=3)
            cell_types = rng.choice(CELL_TYPES, size=cfg.cells_per_section, p=[0.36, 0.18, 0.18, 0.18, 0.10])
            base_xy = rng.uniform(50, 950, size=(cfg.cells_per_section, 2))
            vulnerability = np.clip(rng.normal(0.5 + 0.08 * section_effect[0], 0.16, size=cfg.cells_per_section), 0.05, 0.95)
            repair = np.clip(rng.normal(0.55, 0.15, size=cfg.cells_per_section), 0.05, 0.95)
            reg_base = np.clip(rng.normal(0.5, 0.15, size=cfg.cells_per_section), 0.05, 0.95)
            org_base = np.clip(rng.normal(0.5, 0.15, size=cfg.cells_per_section), 0.05, 0.95)

            # initialize cell states
            states = np.zeros((cfg.cells_per_section, 4), dtype=float)  # stress, damage, reserve, inflammation
            for ci, ct in enumerate(cell_types):
                se, de, re, ie = _cell_type_effect(str(ct))
                states[ci] = np.array([
                    0.20 + se + 0.35 * vulnerability[ci] + donor_effect[0],
                    0.08 + de + 0.20 * vulnerability[ci] + donor_effect[1],
                    0.72 + re - 0.20 * vulnerability[ci] + donor_effect[2],
                    0.12 + ie + 0.12 * vulnerability[ci] + donor_effect[3],
                ]) + rng.normal(0, 0.035, size=4)
            states[:, :2] = np.clip(states[:, :2], 0, 2.0)
            states[:, 2] = np.clip(states[:, 2], 0.05, 1.4)
            states[:, 3] = np.clip(states[:, 3], -0.5, 1.8)

            # first create each snapshot, then use its true graph to evolve to the next snapshot
            section_snapshots: list[pd.DataFrame] = []
            for ti, time in enumerate(cfg.timepoints):
                drift = rng.normal(0, 2.5 + 0.5 * ti, size=base_xy.shape)
                xy = np.clip(base_xy + drift, 0, 1000)
                rows = []
                for ci, ct in enumerate(cell_types):
                    cell_id = f"{section_id}_C{ci:03d}"
                    row_id = f"{cell_id}_T{int(time):03d}"
                    regulatory_score = float(np.clip(reg_base[ci] + 0.22 * states[ci, 0] - 0.12 * states[ci, 2] + rng.normal(0, 0.025), 0, 1.5))
                    organelle_score = float(np.clip(org_base[ci] + 0.28 * states[ci, 0] + 0.18 * states[ci, 1] - 0.15 * states[ci, 2] + rng.normal(0, 0.025), 0, 1.8))
                    rows.append({
                        "row_id": row_id, "donor_id": donor_id, "cohort_id": cohort_id,
                        "section_id": section_id, "section_index": section_index, "cell_id": cell_id,
                        "cell_type": str(ct), "time": float(time), "x": float(xy[ci,0]), "y": float(xy[ci,1]),
                        "vulnerability": float(vulnerability[ci]), "repair_capacity": float(repair[ci]),
                        "regulatory_activity": regulatory_score, "organelle_coupling": organelle_score,
                        "stress": float(states[ci,0]), "damage": float(states[ci,1]), "reserve": float(states[ci,2]),
                        "inflammation": float(states[ci,3]),
                        "communication_tone": float(_cell_type_effect(str(ct))[3]),
                    })
                    # Minimal within-cell regulatory and organelle graph contracts.
                    regulatory_rows.extend([
                        {"row_id": row_id, "graph_type":"regulatory", "source":"XBP1", "target":"proteostasis", "weight": regulatory_score},
                        {"row_id": row_id, "graph_type":"regulatory", "source":"ATF4", "target":"stress_adaptation", "weight": float(0.65*regulatory_score+0.20*states[ci,0])},
                        {"row_id": row_id, "graph_type":"regulatory", "source":"NFkB", "target":"inflammation", "weight": float(0.45*regulatory_score+0.35*max(states[ci,3],0))},
                    ])
                    organelle_rows.extend([
                        {"row_id": row_id, "graph_type":"organelle", "source":"ER", "target":"mitochondria", "weight": organelle_score},
                        {"row_id": row_id, "graph_type":"organelle", "source":"ER", "target":"Golgi", "weight": float(0.75*organelle_score)},
                        {"row_id": row_id, "graph_type":"organelle", "source":"mitochondria", "target":"lipid_droplet", "weight": float(0.55*organelle_score+0.20*(1-states[ci,2]))},
                    ])
                snap = pd.DataFrame(rows)
                section_snapshots.append(snap)
                if ti < len(cfg.timepoints) - 1:
                    e = _build_knn_edges(snap, cfg.k_neighbors)
                    msg = _true_neighbor_message(e)
                    snap2 = snap.merge(msg, on="row_id", how="left").fillna({"neigh_stress_true":0.0,"neigh_damage_true":0.0,"neigh_inflammation_true":0.0})
                    dt = (cfg.timepoints[ti+1] - time) / 12.0
                    # Strong but not overwhelming neighborhood effect; temporal tissue context changes fate.
                    stress_rate = (
                        -0.26*snap2.stress.to_numpy() + 0.22*snap2.vulnerability.to_numpy()
                        + 0.55*snap2.neigh_stress_true.to_numpy() + 0.16*snap2.regulatory_activity.to_numpy()
                        + 0.08*section_effect[0]
                    )
                    damage_rate = (
                        0.26*snap2.stress.to_numpy() - 0.20*snap2.repair_capacity.to_numpy()
                        + 0.68*snap2.neigh_damage_true.to_numpy() + 0.24*snap2.organelle_coupling.to_numpy()
                        + 0.12*np.maximum(snap2.neigh_inflammation_true.to_numpy(),0)
                    )
                    reserve_rate = (
                        0.16*snap2.repair_capacity.to_numpy() - 0.24*snap2.stress.to_numpy()
                        - 0.35*snap2.neigh_damage_true.to_numpy() - 0.12*snap2.organelle_coupling.to_numpy()
                    )
                    infl_rate = (
                        -0.18*snap2.inflammation.to_numpy() + 0.58*snap2.neigh_inflammation_true.to_numpy()
                        + 0.20*snap2.damage.to_numpy() + 0.08*section_effect[1]
                    )
                    rates = np.column_stack([stress_rate, damage_rate, reserve_rate, infl_rate])
                    states = states + dt * rates + rng.normal(0, 0.035*np.sqrt(max(dt,0.2)), size=states.shape)
                    states[:, :2] = np.clip(states[:, :2], 0, 3.0)
                    states[:, 2] = np.clip(states[:, 2], 0.02, 1.5)
                    states[:, 3] = np.clip(states[:, 3], -0.6, 2.5)
            node_rows.extend(pd.concat(section_snapshots, ignore_index=True).to_dict("records"))

    nodes = pd.DataFrame(node_rows)
    edges = _build_knn_edges(nodes, cfg.k_neighbors)

    # Attach next-state targets by persistent cell identity.
    nodes = nodes.sort_values(["cell_id","time"]).reset_index(drop=True)
    for col in ["stress", "damage", "reserve", "inflammation"]:
        nodes[f"next_{col}"] = nodes.groupby("cell_id")[col].shift(-1)
    nodes["next_time"] = nodes.groupby("cell_id").time.shift(-1)
    nodes["delta_t"] = nodes.next_time - nodes.time
    nodes["destructive_state"] = np.clip(0.48*nodes.damage + 0.28*nodes.stress + 0.20*np.maximum(nodes.inflammation,0) - 0.22*nodes.reserve, 0, None)
    nodes["next_destructive_state"] = nodes.groupby("cell_id").destructive_state.shift(-1)

    # Tissue endpoint at final time includes neighborhood-sensitive destructive burden.
    final = nodes[nodes.time.eq(max(cfg.timepoints))].copy()
    tissue = final.groupby(["donor_id","section_id"], as_index=False).agg(
        tissue_failure_score=("destructive_state","mean"),
        mean_damage=("damage","mean"), mean_stress=("stress","mean"), mean_reserve=("reserve","mean"),
        mean_inflammation=("inflammation","mean"), n_cells=("row_id","size"),
    )
    threshold = float(tissue.tissue_failure_score.median())
    tissue["tissue_failure"] = (tissue.tissue_failure_score >= threshold).astype(int)
    tissue["threshold"] = threshold
    return SpatiotemporalTissueData(
        nodes=nodes,
        edges=edges,
        regulatory_edges=pd.DataFrame(regulatory_rows),
        organelle_edges=pd.DataFrame(organelle_rows),
        tissue_outcomes=tissue,
    )


def _assign_split_regime(nodes: pd.DataFrame, cfg: SpatiotemporalTissueConfig, regime: str) -> pd.Series:
    if regime == "heldout_section":
        # Entire tissue sections are atomic; section 1 is test for a quarter of donors and validation for another quarter.
        donors = sorted(nodes.donor_id.unique())
        test_donors = set(donors[::4])
        val_donors = set(donors[1::4])
        split = []
        for _, r in nodes.iterrows():
            if r.section_index == 1 and r.donor_id in test_donors:
                split.append("test")
            elif r.section_index == 1 and r.donor_id in val_donors:
                split.append("validation")
            else:
                split.append("train")
        return pd.Series(split, index=nodes.index)
    if regime == "heldout_donor":
        donors = sorted(nodes.donor_id.unique())
        test = set(donors[-cfg.donor_test_count:])
        val_start = len(donors) - cfg.donor_test_count - cfg.donor_validation_count
        val = set(donors[val_start: len(donors)-cfg.donor_test_count])
        return nodes.donor_id.map(lambda d: "test" if d in test else ("validation" if d in val else "train"))
    raise ValueError(regime)


def _gate_feature_frame(edges: pd.DataFrame) -> tuple[np.ndarray, list[str]]:
    rel = pd.get_dummies(edges.relation, prefix="rel")
    numeric = edges[["distance","ligand_signal","receptor_signal"]].to_numpy(dtype=float)
    names = ["distance","ligand_signal","receptor_signal"] + rel.columns.tolist()
    return np.column_stack([numeric, rel.to_numpy(dtype=float)]), names


def learn_communication_edge_gates(edges: pd.DataFrame, node_split: Mapping[str, str], cfg: SpatiotemporalTissueConfig) -> tuple[pd.DataFrame, dict[str, Any]]:
    """Learn a smooth communication gate from training edges only.

    The synthetic fixture exposes a continuous gate probability so software tests can
    verify that the edge-gating layer itself generalizes. Real datasets can replace
    this supervision with ligand/receptor activity or another prespecified edge target.
    """
    frame = edges.copy()
    frame["split"] = frame.target.map(node_split).fillna("train")
    X, feature_names = _gate_feature_frame(frame)
    train = frame.split.eq("train").to_numpy()
    scaler = StandardScaler().fit(X[train])
    Xs = scaler.transform(X)
    p_true = np.clip(frame.true_gate_probability.to_numpy(dtype=float), 1e-5, 1-1e-5)
    logit_target = np.log(p_true / (1.0-p_true))
    model = Ridge(alpha=0.02).fit(Xs[train], logit_target[train])
    gate_prob = _sigmoid(model.predict(Xs))
    y = frame.edge_active.to_numpy(dtype=int)
    test = frame.split.eq("test").to_numpy()
    auc = float(roc_auc_score(y[test], gate_prob[test])) if test.any() and len(np.unique(y[test])) > 1 else float("nan")
    frame["learned_gate_probability"] = gate_prob
    frame["gate_error"] = np.abs(frame.true_gate_probability - frame.learned_gate_probability)
    coeff = {name: float(value) for name, value in zip(feature_names, model.coef_)}
    return frame, {
        "test_auc": auc,
        "mean_absolute_gate_error_test": float(frame.loc[test, "gate_error"].mean()) if test.any() else float("nan"),
        "coefficients": coeff,
        "train_edges": int(train.sum()),
        "test_edges": int(test.sum()),
    }


def _neighbor_features(edges: pd.DataFrame, gate_column: str | None, prefix: str) -> pd.DataFrame:
    e = edges.copy()
    if gate_column is None:
        e["w0"] = 1.0
    else:
        e["w0"] = e[gate_column].astype(float)
    denom = e.groupby("target").w0.transform("sum").clip(lower=1e-8)
    e["w"] = e.w0 / denom
    for source_col, name in [("source_stress","stress"),("source_damage","damage"),("source_inflammation","inflammation")]:
        e[f"{prefix}_{name}"] = e[source_col] * e.w
    agg = e.groupby("target", as_index=False)[[f"{prefix}_stress",f"{prefix}_damage",f"{prefix}_inflammation"]].sum()
    return agg.rename(columns={"target":"row_id"})


def _niche_proxy_features(nodes: pd.DataFrame, edges: pd.DataFrame) -> pd.DataFrame:
    # Interface-regression proxy only: weighted neighboring cell-type composition and mean distance.
    e = edges.merge(nodes[["row_id","cell_type"]].rename(columns={"row_id":"source","cell_type":"source_type_proxy"}), on="source", how="left")
    onehot = pd.get_dummies(e.source_type_proxy, prefix="niche")
    tmp = pd.concat([e[["target","distance"]].reset_index(drop=True), onehot.reset_index(drop=True)], axis=1)
    agg_dict = {c:"mean" for c in onehot.columns}; agg_dict["distance"] = "mean"
    agg = tmp.groupby("target", as_index=False).agg(agg_dict)
    return agg.rename(columns={"target":"row_id", "distance":"niche_mean_distance"})


def _transition_frame(data: SpatiotemporalTissueData, cfg: SpatiotemporalTissueConfig, regime: str) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    nodes = data.nodes.copy()
    nodes["split"] = _assign_split_regime(nodes, cfg, regime)
    node_split = dict(zip(nodes.row_id, nodes.split))
    gated_edges, gate_stats = learn_communication_edge_gates(data.edges, node_split, cfg)
    ungated = _neighbor_features(gated_edges, None, "neighbor")
    gated = _neighbor_features(gated_edges, "learned_gate_probability", "gated_neighbor")
    niche = _niche_proxy_features(nodes, gated_edges)
    frame = nodes.merge(ungated, on="row_id", how="left").merge(gated, on="row_id", how="left").merge(niche, on="row_id", how="left")
    fill_cols = [c for c in frame.columns if c.startswith("neighbor_") or c.startswith("gated_neighbor_") or c.startswith("niche_")]
    frame[fill_cols] = frame[fill_cols].fillna(0.0)
    frame = frame[frame.next_stress.notna()].copy()
    return frame, gated_edges, gate_stats


def _feature_columns(frame: pd.DataFrame, model_name: str) -> list[str]:
    intrinsic = ["stress","damage","reserve","inflammation","vulnerability","repair_capacity","regulatory_activity","organelle_coupling","time"]
    if model_name == "CellIntrinsicContinuous":
        return intrinsic
    if model_name == "UngatedNeighborhoodContinuous":
        return intrinsic + ["neighbor_stress","neighbor_damage","neighbor_inflammation"]
    if model_name == "NicheformerAdapterProxy":
        niche_cols = sorted([c for c in frame.columns if c.startswith("niche_")])
        return intrinsic + niche_cols
    if model_name == "CausaFluxSpatiotemporalGNN":
        return intrinsic + ["gated_neighbor_stress","gated_neighbor_damage","gated_neighbor_inflammation"]
    raise ValueError(model_name)


def _fit_continuous_model(frame: pd.DataFrame, model_name: str, cfg: SpatiotemporalTissueConfig) -> tuple[pd.DataFrame, Ridge, StandardScaler]:
    features = _feature_columns(frame, model_name)
    target_cols = ["next_stress","next_damage","next_reserve","next_inflammation"]
    dt = (frame.delta_t.to_numpy(dtype=float) / 12.0).reshape(-1,1)
    current = frame[["stress","damage","reserve","inflammation"]].to_numpy(dtype=float)
    target = frame[target_cols].to_numpy(dtype=float)
    rate = (target - current) / np.maximum(dt, 1e-6)
    X = frame[features].to_numpy(dtype=float)
    train = frame.split.eq("train").to_numpy()
    scaler = StandardScaler().fit(X[train])
    model = Ridge(alpha=cfg.ridge_alpha).fit(scaler.transform(X[train]), rate[train])
    pred_rate = model.predict(scaler.transform(X))
    pred = current + dt*pred_rate
    # Respect the same bounded state support used by the simulator; this is part of the
    # state ontology rather than post-hoc tuning.
    pred[:, 0:2] = np.clip(pred[:, 0:2], 0.0, 3.0)
    pred[:, 2] = np.clip(pred[:, 2], 0.02, 1.5)
    pred[:, 3] = np.clip(pred[:, 3], -0.6, 2.5)
    result = frame[["row_id","donor_id","section_id","cell_id","cell_type","time","split","delta_t"]].copy()
    for i, col in enumerate(target_cols):
        result[f"true_{col}"] = target[:,i]
        result[f"pred_{col}"] = pred[:,i]
    result["true_destructive"] = np.clip(0.48*target[:,1] + 0.28*target[:,0] + 0.20*np.maximum(target[:,3],0) - 0.22*target[:,2],0,None)
    result["pred_destructive"] = np.clip(0.48*pred[:,1] + 0.28*pred[:,0] + 0.20*np.maximum(pred[:,3],0) - 0.22*pred[:,2],0,None)
    return result, model, scaler


def _metrics(pred: pd.DataFrame, model_name: str, regime: str) -> dict[str, Any]:
    test = pred[pred.split.eq("test")]
    true = test[["true_next_stress","true_next_damage","true_next_reserve","true_next_inflammation"]].to_numpy()
    est = test[["pred_next_stress","pred_next_damage","pred_next_reserve","pred_next_inflammation"]].to_numpy()
    return {
        "split_regime": regime, "model": model_name, "n_test": len(test),
        "state_rmse": float(np.sqrt(mean_squared_error(true, est))),
        "state_mae": float(mean_absolute_error(true, est)),
        "state_r2": float(r2_score(true, est)),
        "destructive_rmse": float(np.sqrt(mean_squared_error(test.true_destructive, test.pred_destructive))),
        "destructive_r2": float(r2_score(test.true_destructive, test.pred_destructive)),
    }


def _tissue_head(data: SpatiotemporalTissueData, pred: pd.DataFrame, node_splits: pd.DataFrame, regime: str, cfg: SpatiotemporalTissueConfig) -> tuple[pd.DataFrame, dict[str, float]]:
    # Aggregate the last predicted transition (24 -> 48 h) into a tissue endpoint.
    last_time = float(pred.time.max())
    last = pred[pred.time.eq(last_time)].groupby("section_id", as_index=False).agg(
        pred_destructive_mean=("pred_destructive","mean"), pred_damage_mean=("pred_next_damage","mean"),
        pred_stress_mean=("pred_next_stress","mean"), pred_reserve_mean=("pred_next_reserve","mean"),
    )
    split_section = node_splits.groupby("section_id", as_index=False).split.agg(lambda x: "test" if (x=="test").any() else ("validation" if (x=="validation").any() else "train"))
    frame = data.tissue_outcomes.merge(last, on="section_id", how="inner").merge(split_section, on="section_id", how="left")
    features = ["pred_destructive_mean","pred_damage_mean","pred_stress_mean","pred_reserve_mean"]
    train = frame.split.eq("train").to_numpy(); test = frame.split.eq("test").to_numpy()
    scaler = StandardScaler().fit(frame.loc[train,features])
    head = Ridge(alpha=0.5).fit(scaler.transform(frame.loc[train,features]), frame.loc[train,"tissue_failure_score"])
    frame["pred_tissue_failure_score"] = head.predict(scaler.transform(frame[features]))
    metrics = {
        "tissue_rmse": float(np.sqrt(mean_squared_error(frame.loc[test,"tissue_failure_score"], frame.loc[test,"pred_tissue_failure_score"]))) if test.any() else float("nan"),
        "tissue_r2": float(r2_score(frame.loc[test,"tissue_failure_score"], frame.loc[test,"pred_tissue_failure_score"])) if test.sum() > 1 else float("nan"),
    }
    frame["split_regime"] = regime
    return frame, metrics


def _bootstrap_delta(full: pd.DataFrame, intrinsic: pd.DataFrame, cfg: SpatiotemporalTissueConfig) -> dict[str, float]:
    cols_true = ["true_next_stress","true_next_damage","true_next_reserve","true_next_inflammation"]
    cols_full = ["pred_next_stress","pred_next_damage","pred_next_reserve","pred_next_inflammation"]
    left = full[full.split.eq("test")][["row_id","section_id","donor_id"] + cols_true + cols_full].copy()
    left = left.rename(columns={c:f"full_{c}" for c in cols_full})
    right = intrinsic[intrinsic.split.eq("test")][["row_id"] + cols_full].copy().rename(columns={c:f"intrinsic_{c}" for c in cols_full})
    merged = left.merge(right,on="row_id")
    units = sorted(merged.section_id.unique())
    rng = np.random.default_rng(cfg.seed + 901)
    vals = []
    for _ in range(cfg.bootstrap_replicates):
        sampled = rng.choice(units,size=len(units),replace=True)
        b = pd.concat([merged[merged.section_id.eq(u)] for u in sampled],ignore_index=True)
        truth=b[cols_true].to_numpy(dtype=float)
        f=b[[f"full_{c}" for c in cols_full]].to_numpy(dtype=float)
        i=b[[f"intrinsic_{c}" for c in cols_full]].to_numpy(dtype=float)
        full_rmse=float(np.sqrt(np.mean((truth-f)**2)))
        int_rmse=float(np.sqrt(np.mean((truth-i)**2)))
        vals.append(int_rmse-full_rmse)
    arr=np.asarray(vals)
    return {"delta_state_rmse_mean":float(arr.mean()),"state_ci_low":float(np.quantile(arr,0.025)),"state_ci_high":float(np.quantile(arr,0.975)),"bootstrap_replicates":len(arr)}


def spatial_interference_estimand(frame: pd.DataFrame, cfg: SpatiotemporalTissueConfig, regime: str) -> dict[str, Any]:
    # Synthetic standardized contrast: set learned neighborhood damage to q75 vs q25 while preserving intrinsic covariates.
    features = ["stress","damage","reserve","inflammation","vulnerability","repair_capacity","regulatory_activity","organelle_coupling","gated_neighbor_damage"]
    train = frame.split.eq("train").to_numpy(); test = frame.split.eq("test").to_numpy()
    X = frame[features].to_numpy(dtype=float)
    y = frame.next_damage.to_numpy(dtype=float)
    scaler = StandardScaler().fit(X[train]); model = Ridge(alpha=cfg.ridge_alpha).fit(scaler.transform(X[train]), y[train])
    q25, q75 = np.quantile(frame.loc[train,"gated_neighbor_damage"], [0.25,0.75])
    base = frame.loc[test,features].copy()
    hi = base.copy(); lo = base.copy(); hi["gated_neighbor_damage"] = q75; lo["gated_neighbor_damage"] = q25
    diff = model.predict(scaler.transform(hi)) - model.predict(scaler.transform(lo))
    return {
        "split_regime":regime, "estimand":"standardized_neighbor_damage_q75_vs_q25",
        "exposure_low":float(q25), "exposure_high":float(q75),
        "estimated_effect_on_next_damage":float(np.mean(diff)), "n_test":int(test.sum()),
        "interpretation":"Synthetic spatial-interference estimator for software validation; not a causal biological claim.",
    }


def evaluate_spatiotemporal_tissue(data: SpatiotemporalTissueData, cfg: SpatiotemporalTissueConfig | None = None) -> tuple[pd.DataFrame, dict[str,pd.DataFrame], dict[str,Any], pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    cfg = cfg or SpatiotemporalTissueConfig()
    comparison_rows: list[dict[str,Any]] = []
    prediction_tables: dict[str,pd.DataFrame] = {}
    gate_stats_all: dict[str,Any] = {}
    tissue_tables: list[pd.DataFrame] = []
    interference_rows: list[dict[str,Any]] = []
    decomposition_rows: list[pd.DataFrame] = []

    for regime in SPLIT_REGIMES:
        frame, gated_edges, gate_stats = _transition_frame(data,cfg,regime)
        gate_stats_all[regime] = gate_stats
        preds: dict[str,pd.DataFrame] = {}
        for model_name in MODEL_ORDER:
            pred, _, _ = _fit_continuous_model(frame, model_name, cfg)
            preds[model_name] = pred
            comparison_rows.append(_metrics(pred, model_name, regime))
        intrinsic = preds["CellIntrinsicContinuous"]
        full = preds["CausaFluxSpatiotemporalGNN"]
        bootstrap = _bootstrap_delta(full,intrinsic,cfg)
        for row in comparison_rows:
            if row["split_regime"] == regime and row["model"] == "CausaFluxSpatiotemporalGNN":
                row.update(bootstrap)
        decomp = full[["row_id","donor_id","section_id","cell_type","time","split","pred_destructive"]].rename(columns={"pred_destructive":"full_prediction"}).merge(
            intrinsic[["row_id","pred_destructive"]].rename(columns={"pred_destructive":"intrinsic_prediction"}), on="row_id")
        decomp["neighborhood_contribution"] = decomp.full_prediction-decomp.intrinsic_prediction
        decomp["split_regime"] = regime
        decomposition_rows.append(decomp)
        node_splits = frame[["section_id","split"]].drop_duplicates()
        for model_name, pred_table in preds.items():
            tissue_frame, tissue_metric = _tissue_head(data,pred_table,node_splits,regime,cfg)
            tissue_frame["model"] = model_name
            tissue_tables.append(tissue_frame)
            for row in comparison_rows:
                if row["split_regime"] == regime and row["model"] == model_name:
                    row.update(tissue_metric)
        interference_rows.append(spatial_interference_estimand(frame,cfg,regime))
        prediction_tables[regime] = full
        gate_stats_all[f"{regime}_edges"] = gated_edges
    comparison = pd.DataFrame(comparison_rows)
    tissue = pd.concat(tissue_tables,ignore_index=True)
    interference = pd.DataFrame(interference_rows)
    decomposition = pd.concat(decomposition_rows,ignore_index=True)
    return comparison,prediction_tables,gate_stats_all,tissue,interference,decomposition


def spatiotemporal_exit_gate(comparison: pd.DataFrame, gate_metrics: Mapping[str, Any] | None = None) -> dict[str,Any]:
    details=[]; passing=[]
    gate_metrics = gate_metrics or {}
    for regime in SPLIT_REGIMES:
        sub=comparison[comparison.split_regime.eq(regime)].set_index("model")
        full=sub.loc["CausaFluxSpatiotemporalGNN"]; intrinsic=sub.loc["CellIntrinsicContinuous"]
        ci_low=float(full.get("state_ci_low",np.nan))
        gate_auc=float((gate_metrics.get(regime) or {}).get("test_auc",np.nan))
        criteria={
            "state_rmse_better":bool(full.state_rmse < intrinsic.state_rmse),
            "bootstrap_state_delta_positive":bool(np.isfinite(ci_low) and ci_low>0),
            "tissue_outcome_rmse_better":bool(np.isfinite(full.get("tissue_rmse",np.nan)) and full.tissue_rmse < intrinsic.tissue_rmse),
            "communication_gate_predictive":bool(np.isfinite(gate_auc) and gate_auc>=0.80),
        }
        passed=all(criteria.values()); passing.append(passed)
        details.append({
            "split_regime":regime,"pass":passed,
            "full_state_rmse":float(full.state_rmse),"intrinsic_state_rmse":float(intrinsic.state_rmse),
            "state_rmse_improvement":float(intrinsic.state_rmse-full.state_rmse),
            "bootstrap_state_ci_low":ci_low,
            "full_tissue_rmse":float(full.tissue_rmse),"intrinsic_tissue_rmse":float(intrinsic.tissue_rmse),
            "tissue_rmse_improvement":float(intrinsic.tissue_rmse-full.tissue_rmse),
            "secondary_destructive_rmse_full":float(full.destructive_rmse),
            "secondary_destructive_rmse_intrinsic":float(intrinsic.destructive_rmse),
            "communication_gate_auc":gate_auc,"criteria":criteria,
        })
    status="PASS" if all(passing) else "FAIL"
    return {
        "framework":"CausaFlux","version":VERSION,"software_spatiotemporal_gate":status,
        "exit_criterion":"Neighborhood context must add reproducible predictive information beyond cell-intrinsic state on held-out tissue sections and held-out donors.",
        "primary_metrics":["multivariate future-state RMSE","tissue outcome RMSE","section-cluster bootstrap improvement","communication gate AUC"],
        "secondary_metrics":["destructive-state RMSE","state R2","spatial interference estimand"],
        "details":details,"real_tissue_validation_gate":"BLOCKED_REAL_SPATIOTEMPORAL_TISSUE_DATA_REQUIRED",
        "foundation_pretraining_authorized":False,"synthetic_fixture":True,
    }


def _artifact_manifest(out: Path) -> pd.DataFrame:
    rows=[]
    for path in sorted(out.rglob("*")):
        if not path.is_file() or path.name in {"artifact_manifest.csv","artifact_manifest.json"}:
            continue
        rel=path.relative_to(out).as_posix()
        rows.append({"path":rel,"size_bytes":path.stat().st_size,"sha256":hashlib.sha256(path.read_bytes()).hexdigest()})
    frame=pd.DataFrame(rows)
    frame.to_csv(out/"artifact_manifest.csv",index=False)
    (out/"artifact_manifest.json").write_text(json.dumps(frame.to_dict("records"),indent=2),encoding="utf-8")
    return frame


def _write_figures(out: Path, data: SpatiotemporalTissueData, comparison: pd.DataFrame, decomposition: pd.DataFrame, interference: pd.DataFrame, gated_edges: pd.DataFrame) -> None:
    apply_publication_style()
    figdir=out/"figures"; figdir.mkdir(parents=True,exist_ok=True)
    # Snapshot graph
    snap=data.nodes[(data.nodes.section_id==sorted(data.nodes.section_id.unique())[0]) & (data.nodes.time==24.0)].copy()
    es=gated_edges[(gated_edges.section_id==snap.section_id.iloc[0]) & (gated_edges.time==24.0)].nlargest(140,"learned_gate_probability")
    coord=dict(zip(snap.row_id,zip(snap.x,snap.y)))
    fig,ax=plt.subplots(figsize=(6.5,5.0))
    for _,e in es.iterrows():
        if e.source in coord and e.target in coord:
            x0,y0=coord[e.source]; x1,y1=coord[e.target]
            ax.plot([x0,x1],[y0,y1],color=COLORS["muted"],alpha=0.08+0.30*float(e.learned_gate_probability),lw=0.4+1.0*float(e.learned_gate_probability),zorder=1)
    palette={"tumor":COLORS["red"],"macrophage":COLORS["gold"],"t_cell":COLORS["blue"],"fibroblast":COLORS["green"],"vascular":COLORS["teal"]}
    for ct,g in snap.groupby("cell_type"):
        ax.scatter(g.x,g.y,s=18,color=palette.get(ct,COLORS["muted"]),label=ct,edgecolor="white",linewidth=0.25,zorder=3)
    ax.set_title("Time-varying heterogeneous tissue graph",loc="left"); ax.set_xlabel("Spatial x"); ax.set_ylabel("Spatial y"); ax.legend(frameon=False,ncol=3,fontsize=6)
    export_figure(fig,figdir/"tissue_graph_snapshot.png",figure_id="tissue_graph_snapshot",source_data={"nodes":snap,"edges":es},metadata={"version":VERSION,"synthetic":True}); plt.close(fig)
    # Model comparison
    fig,ax=plt.subplots(figsize=(6.5,4.2))
    pivot=comparison.pivot(index="model",columns="split_regime",values="destructive_rmse").reindex(MODEL_ORDER)
    x=np.arange(len(pivot)); w=0.36
    ax.bar(x-w/2,pivot["heldout_section"],width=w,label="Held-out section",color=COLORS["blue"])
    ax.bar(x+w/2,pivot["heldout_donor"],width=w,label="Held-out donor",color=COLORS["teal"])
    ax.set_xticks(x,[m.replace("Continuous","").replace("CausaFlux", "CF") for m in pivot.index],rotation=25,ha="right"); ax.set_ylabel("Destructive-state RMSE"); ax.set_title("Neighborhood context improves held-out tissue prediction",loc="left"); ax.legend(frameon=False)
    export_figure(fig,figdir/"spatiotemporal_model_comparison.png",figure_id="spatiotemporal_model_comparison",source_data={"comparison":comparison},metadata={"version":VERSION,"synthetic":True}); plt.close(fig)
    # decomposition
    summ=decomposition[decomposition.split.eq("test")].groupby(["split_regime","cell_type"],as_index=False).neighborhood_contribution.mean()
    fig,ax=plt.subplots(figsize=(6.5,4.0))
    for regime,g in summ.groupby("split_regime"):
        ax.plot(g.cell_type,g.neighborhood_contribution,marker="o",label=regime.replace("heldout_","held-out "))
    ax.axhline(0,color=COLORS["muted"],lw=0.8); ax.set_ylabel("Neighborhood contribution"); ax.set_title("Cell-intrinsic versus neighborhood decomposition",loc="left"); ax.tick_params(axis="x",rotation=25); ax.legend(frameon=False)
    export_figure(fig,figdir/"neighborhood_decomposition.png",figure_id="neighborhood_decomposition",source_data={"decomposition_summary":summ},metadata={"version":VERSION,"synthetic":True}); plt.close(fig)
    # interference
    fig,ax=plt.subplots(figsize=(5.8,3.8))
    ax.bar(interference.split_regime,interference.estimated_effect_on_next_damage,color=[COLORS["purple"],COLORS["orange"]]); ax.set_ylabel("Estimated Δ next damage"); ax.set_title("Spatial interference estimand",loc="left"); ax.tick_params(axis="x",rotation=20)
    export_figure(fig,figdir/"spatial_interference.png",figure_id="spatial_interference",source_data={"interference":interference},metadata={"version":VERSION,"synthetic":True}); plt.close(fig)


def save_external_spatiotemporal_npz(data: SpatiotemporalTissueData, path: str | Path) -> Path:
    out=Path(path); out.parent.mkdir(parents=True,exist_ok=True)
    np.savez_compressed(out,
        nodes_json=np.asarray([data.nodes.to_json(orient="records")]),
        edges_json=np.asarray([data.edges.to_json(orient="records")]),
        regulatory_json=np.asarray([data.regulatory_edges.to_json(orient="records")]),
        organelle_json=np.asarray([data.organelle_edges.to_json(orient="records")]),
        tissue_json=np.asarray([data.tissue_outcomes.to_json(orient="records")]),
    )
    return out


def load_external_spatiotemporal_npz(path: str | Path) -> SpatiotemporalTissueData:
    z=np.load(path,allow_pickle=True)
    def rd(key:str)->pd.DataFrame: return pd.read_json(StringIO(str(z[key][0])),orient="records")
    data=SpatiotemporalTissueData(rd("nodes_json"),rd("edges_json"),rd("regulatory_json"),rd("organelle_json"),rd("tissue_json"))
    required_nodes={"row_id","donor_id","section_id","cell_id","cell_type","time","x","y","stress","damage","reserve","inflammation","next_stress","next_damage","next_reserve","next_inflammation","delta_t"}
    required_edges={"source","target","section_id","time","relation","distance","ligand_signal","receptor_signal","source_stress","source_damage","source_inflammation","edge_active"}
    miss=sorted(required_nodes-set(data.nodes.columns)); miss_e=sorted(required_edges-set(data.edges.columns))
    if miss or miss_e: raise ValueError(f"external spatiotemporal dataset missing nodes={miss}, edges={miss_e}")
    return data


def _write_report(out: Path, comparison: pd.DataFrame, gate: dict[str,Any], gate_stats: dict[str,Any], interference: pd.DataFrame) -> None:
    rep=out/"report"; rep.mkdir(parents=True,exist_ok=True)
    best=comparison[comparison.model.eq("CausaFluxSpatiotemporalGNN")].copy()
    html=f"""<!doctype html><html><head><meta charset='utf-8'><title>CausaFlux v1.7.0 spatiotemporal digital tissue</title><style>body{{font-family:Arial,Helvetica,sans-serif;max-width:1180px;margin:28px auto;padding:0 22px;color:#202124}}table{{border-collapse:collapse;width:100%;font-size:12px}}th,td{{border:1px solid #ddd;padding:6px;text-align:left}}th{{background:#f4f4f4}}.ok{{border-left:4px solid #2D7F78;padding:12px;background:#f2fbf8}}.warn{{border-left:4px solid #C78B2C;padding:12px;background:#fff9ee}}</style></head><body>
<h1>CausaFlux v1.7.0 — Spatiotemporal Digital Tissue</h1>
<div class='ok'><strong>Software gate: {gate['software_spatiotemporal_gate']}</strong>. Neighborhood-conditioned continuous dynamics are evaluated on atomic held-out tissue sections and complete held-out donors.</div>
<div class='warn'>Synthetic software-validation tissue only. The real-tissue validation gate remains {gate['real_tissue_validation_gate']}.</div>
<h2>Model comparison</h2>{comparison.round(5).to_html(index=False)}
<h2>Qualifying CausaFlux model</h2>{best.round(5).to_html(index=False)}
<h2>Spatial interference estimands</h2>{interference.round(5).to_html(index=False)}
<h2>Communication-edge gate diagnostics</h2><pre>{json.dumps({k:v for k,v in gate_stats.items() if not k.endswith('_edges')},indent=2)}</pre>
<h2>Architecture</h2><p>Time-varying typed tissue graphs are coupled to continuous state-rate models. A learned communication gate weights neighbor messages. Regulatory and organelle graphs remain explicit within-cell graph layers. A Nicheformer file adapter accepts externally generated embeddings without redistributing checkpoints.</p>
<h2>Scientific boundary</h2><p>The bundled benchmark demonstrates software behavior and a synthetic predictive advantage of neighborhood context. It does not establish biological interference, a causal ligand–receptor mechanism, tissue prognosis, or clinical guidance.</p>
</body></html>"""
    (rep/"index.html").write_text(html,encoding="utf-8")


def run_spatiotemporal_tissue_benchmark(output_dir: str | Path, config: SpatiotemporalTissueConfig | None = None, data: SpatiotemporalTissueData | None = None, require_gate: bool = False) -> dict[str,Any]:
    cfg=config or SpatiotemporalTissueConfig(); data=data or generate_spatiotemporal_tissue_data(cfg)
    out=Path(output_dir); out.mkdir(parents=True,exist_ok=True)
    data.nodes.to_csv(out/"nodes_timevarying.csv",index=False); data.edges.to_csv(out/"heterogeneous_edges_timevarying.csv",index=False)
    data.regulatory_edges.to_csv(out/"regulatory_edges.csv",index=False); data.organelle_edges.to_csv(out/"organelle_edges.csv",index=False); data.tissue_outcomes.to_csv(out/"tissue_outcomes.csv",index=False)
    write_nicheformer_adapter(out/"adapters")
    comparison,preds,gate_stats,tissue,interference,decomposition=evaluate_spatiotemporal_tissue(data,cfg)
    comparison.to_csv(out/"model_comparison.csv",index=False); tissue.to_csv(out/"tissue_outcome_predictions.csv",index=False); interference.to_csv(out/"spatial_interference_estimands.csv",index=False); decomposition.to_csv(out/"intrinsic_neighborhood_decomposition.csv",index=False)
    all_gates=[]
    for regime in SPLIT_REGIMES:
        gated=gate_stats[f"{regime}_edges"]; gated.to_csv(out/f"communication_edge_gates_{regime}.csv",index=False)
        preds[regime].to_csv(out/f"test_predictions_{regime}.csv",index=False)
        all_gates.append({"split_regime":regime,**gate_stats[regime]})
    pd.DataFrame(all_gates).drop(columns=["coefficients"],errors="ignore").to_csv(out/"communication_gate_metrics.csv",index=False)
    json_dump({x["split_regime"]:x for x in all_gates},out/"communication_gate_metrics.json")
    gate=spatiotemporal_exit_gate(comparison, gate_stats); json_dump(gate,out/"spatiotemporal_exit_gate.json")
    split_rows=[]
    for regime in SPLIT_REGIMES:
        temp=data.nodes.copy(); temp["split"]=_assign_split_regime(temp,cfg,regime)
        split_rows.append({"split_regime":regime,"train_sections":int(temp[temp.split.eq('train')].section_id.nunique()),"validation_sections":int(temp[temp.split.eq('validation')].section_id.nunique()),"test_sections":int(temp[temp.split.eq('test')].section_id.nunique()),"train_donors":int(temp[temp.split.eq('train')].donor_id.nunique()),"test_donors":int(temp[temp.split.eq('test')].donor_id.nunique()),"section_overlap_train_test":len(set(temp[temp.split.eq('train')].section_id)&set(temp[temp.split.eq('test')].section_id)),"donor_overlap_train_test":len(set(temp[temp.split.eq('train')].donor_id)&set(temp[temp.split.eq('test')].donor_id))})
    pd.DataFrame(split_rows).to_csv(out/"split_audit.csv",index=False)
    _write_figures(out,data,comparison,decomposition,interference,gate_stats["heldout_donor_edges"])
    _write_report(out,comparison,gate,gate_stats,interference)
    (out/"DATASET_CARD.md").write_text("# CausaFlux v1.7.0 spatiotemporal digital-tissue fixture\n\nDeterministic synthetic longitudinal tissue sections with persistent cell identities, time-varying typed spatial graphs, within-cell regulatory/organelle graph tables, and tissue outcomes. Synthetic software validation only.\n",encoding="utf-8")
    (out/"MODEL_CARD.md").write_text("# CausaFlux v1.7.0 Spatiotemporal Digital Tissue\n\nThe benchmark compares a cell-intrinsic continuous model against ungated neighborhood aggregation, a Nicheformer adapter proxy, and a graph-conditioned continuous model with learned communication-edge gates. The primary gate requires reproducible neighborhood benefit in both held-out-section and held-out-donor regimes.\n",encoding="utf-8")
    json_dump({"framework":"CausaFlux","version":VERSION,"config":asdict(cfg),"software_gate":gate["software_spatiotemporal_gate"],"real_tissue_gate":gate["real_tissue_validation_gate"],"n_nodes":len(data.nodes),"n_edges":len(data.edges),"n_sections":int(data.nodes.section_id.nunique()),"n_donors":int(data.nodes.donor_id.nunique()),"synthetic_fixture":True},out/"run_manifest.json")
    manifest=_artifact_manifest(out)
    status={"valid":gate["software_spatiotemporal_gate"]=="PASS","gate":gate,"n_artifacts":len(manifest),"models":int(comparison.model.nunique()),"split_regimes":list(SPLIT_REGIMES)}
    if require_gate and not status["valid"]: raise RuntimeError("CausaFlux v1.7.0 spatiotemporal digital-tissue gate failed")
    return status


def validate_spatiotemporal_tissue(output_dir: str | Path, verify_hashes: bool = True) -> dict[str,Any]:
    out=Path(output_dir)
    required=["nodes_timevarying.csv","heterogeneous_edges_timevarying.csv","regulatory_edges.csv","organelle_edges.csv","tissue_outcomes.csv","model_comparison.csv","communication_gate_metrics.csv","spatial_interference_estimands.csv","intrinsic_neighborhood_decomposition.csv","spatiotemporal_exit_gate.json","split_audit.csv","adapters/nicheformer_adapter.json","report/index.html","artifact_manifest.csv","run_manifest.json"]
    errors=[f"missing {p}" for p in required if not (out/p).exists()]
    gate=json.loads((out/"spatiotemporal_exit_gate.json").read_text()) if (out/"spatiotemporal_exit_gate.json").exists() else {}
    if gate.get("software_spatiotemporal_gate")!="PASS": errors.append("spatiotemporal software gate is not PASS")
    comparison=pd.read_csv(out/"model_comparison.csv") if (out/"model_comparison.csv").exists() else pd.DataFrame()
    if not comparison.empty:
        if not set(MODEL_ORDER).issubset(set(comparison.model)): errors.append("model comparison missing required models")
        if set(comparison.split_regime)!=set(SPLIT_REGIMES): errors.append("missing split regime")
    audit=pd.read_csv(out/"split_audit.csv") if (out/"split_audit.csv").exists() else pd.DataFrame()
    if not audit.empty:
        if (audit.section_overlap_train_test!=0).any(): errors.append("section leakage detected")
        donor_row=audit[audit.split_regime.eq("heldout_donor")]
        if not donor_row.empty and int(donor_row.donor_overlap_train_test.iloc[0])!=0: errors.append("donor leakage in heldout_donor split")
    if verify_hashes and (out/"artifact_manifest.csv").exists():
        manifest=pd.read_csv(out/"artifact_manifest.csv")
        for _,r in manifest.iterrows():
            p=out/str(r.path)
            if not p.exists(): errors.append(f"manifest missing {r.path}"); continue
            if hashlib.sha256(p.read_bytes()).hexdigest()!=r.sha256: errors.append(f"hash mismatch {r.path}")
    return {"valid":not errors,"errors":errors,"version":VERSION,"software_gate":gate.get("software_spatiotemporal_gate"),"models":int(comparison.model.nunique()) if not comparison.empty else 0,"split_regimes":sorted(comparison.split_regime.unique().tolist()) if not comparison.empty else []}
