#!/usr/bin/env bash
set -euo pipefail
PYTHON_BIN="${1:-python3}"
CONFIG="${2:-configs/cancer_closed_loop_v1.7.0.yaml}"
OUTPUT="${3:-causaflux_v1.7.0_output}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
rm -rf "$OUTPUT"
export PYTHONPATH="$ROOT/src${PYTHONPATH:+:$PYTHONPATH}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export PYTHONWARNINGS="${PYTHONWARNINGS:-ignore}"
"$PYTHON_BIN" -u scripts/stage_baseline.py --config "$CONFIG" --output "$OUTPUT"
"$PYTHON_BIN" -u scripts/stage_spatial_causal.py --config "$CONFIG" --output "$OUTPUT"
"$PYTHON_BIN" -u scripts/stage_causal_effects.py --config "$CONFIG" --output "$OUTPUT"
"$PYTHON_BIN" -u scripts/stage_therapeutics.py --config "$CONFIG" --output "$OUTPUT"
"$PYTHON_BIN" -u scripts/stage_biomarkers.py --config "$CONFIG" --output "$OUTPUT"
"$PYTHON_BIN" -u scripts/stage_active_learning.py --config "$CONFIG" --output "$OUTPUT"
"$PYTHON_BIN" -u scripts/stage_neurobiology.py --config "$CONFIG" --output "$OUTPUT"
"$PYTHON_BIN" -u scripts/stage_finalize.py --config "$CONFIG" --output "$OUTPUT"
bash scripts/publication_build.sh "$PYTHON_BIN" "$OUTPUT"
"$PYTHON_BIN" -u scripts/stage_platform.py --output "$OUTPUT"
"$PYTHON_BIN" scripts/verify_release.py "$OUTPUT"
printf 'CausaFlux v1.7.0 complete: %s\n' "$OUTPUT"
printf 'HTML report: %s/report/index.html\n' "$OUTPUT"
